### ISSUE TITLE
Macro-in-macro usage not identified (edge case?)

### ISSUE THREAD

**Issue by Elchi3** [SebastianZ/templateScraper#2]
The output says https://developer.mozilla.org/en-US/docs/Template:DNTGChapters is used nowhere, but https://developer.mozilla.org/en-US/docs/Template:DNTGToC uses it.

**Comment by Elchi3** [comment]
Another example "L10n_Common" or "L10n_JavaScript" are used in https://developer.mozilla.org/en-US/docs/Template:Jsref for example.

**Comment by SebastianZ** [comment]
> The output says https://developer.mozilla.org/en-US/docs/Template:DNTGChapters is used nowhere, but https://developer.mozilla.org/en-US/docs/Template:DNTGToC uses it.

This is very edge case, I think. `{{DNTGChapters}}` is obviously used indirectly by `{{DNTGToC}}` as a parameter for `{{ChapterTOC}}`, i.e. via `template($0)`.
Honestly, I have no idea yet how to get that info, so I'm open for suggestions.

> Another example "L10n_Common" or "L10n_JavaScript" are used in https://developer.mozilla.org/en-US/docs/Template:Jsref for example.

This got fixed by issue #3.

Sebastian

**Comment by SebastianZ** [comment]
Got an idea, but it's somewhat complicated:
1. Check whether a template has a `template($0)` call in it.
2. Download all pages that are calling the related macro.
3. Check each page for calls to the macro and extract its first parameter (which is the name of the included template).
4. Add the calling template to all found templates.
5. Check all other templates for calls to it and extract its first parameter (which is the name of the included template).
6. Add the calling template to all found templates.

Sebastian

**Comment by SebastianZ** [comment]
I've finally fixed this. Hopefully I caught all cases but it looks like there are only two templates, which are dynamically calling other templates, 'autoPreviousNext' and 'ChapterTOC'.

I've also updated the searchResults.html.

Sebastian
